### ISSUE TITLE
Relatives buggy with mj-include

### ISSUE THREAD

**Issue by deanorhan** [mjmlio/gulp-mjml#32]
Having problems with the new changes for relative URLs in mj-inlcude tags. Compiling with the MJML commandline tool works but when using gulp-mjml we get the error:

Error: ENOENT: no such file or directory, open '../freemarker/mjml/ommon/Attributes.mjml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at checkIncludeHash (/Users/dean/Documents/Workspace/bobe/build/gulpfile.js:447:29)
    at /Users/dean/Documents/Workspace/bobe/build/gulpfile.js:393:24
    at DestroyableTransform.modifyFile [as _transform] (/Users/dean/Documents/Workspace/bobe/node_modules/gulp-tap/lib/tap.js:53:11)
    at DestroyableTransform.Transform._read (/Users/dean/Documents/Workspace/bobe/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/dean/Documents/Workspace/bobe/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/dean/Documents/Workspace/bobe/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/dean/Documents/Workspace/bobe/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/Users/dean/Documents/Workspace/bobe/node_modules/readable-stream/lib/_stream_writable.js:322:11)

When we use the tag:

&lt;mj-include path="../common/Attributes.mjml" /&gt;

**Comment by iRyusa** [comment]
`Error: ENOENT: no such file or directory, open '../freemarker/mjml/ommon/Attributes.mjml'`
Looks like a typo `ommon`

Did you tried the `2.3` version ?

**Comment by deanorhan** [comment]
We are using 2.3.0.

**Comment by iRyusa** [comment]
In `2.3` relative is now from file that does the include instead of the current pwd. Did it works on older `gulp-mjml` ?

**Comment by deanorhan** [comment]
Yes it did. Previously we had the URL as ../freemarker/mjml/email/common/Attributes.mjml in the include, since this was relative to the location of the gulp file. Since updating we've been updating our templates to be relative from the actual file, i.e. ../common/Attributes.mjml. This is breaking with that error I listed above.

Strange thing is it works when we change the relative to be ../../../../freemarker/mjml/email/common/Attributes.mjml. So all the way down and all the way back up.

**Comment by deanorhan** [comment]
Not sure on that one, have to condense the workspace quite a bit.
Tried something just to see and strangly adding a space fixed things:
&lt;mj-include path="../ common/Attributes.mjml" /&gt;

**Comment by deanorhan** [comment]
I'll try a get a repo up, workspace need to be condensed quite a bit.

**Comment by deanorhan** [comment]
While trying to simplify things I've found that its actually some of our other build steps causing the issue. It wasn't updated with the change for includes being relative to the files properly.

Sorry for this.

**Comment by iRyusa** [comment]
👌 then
