### ISSUE TITLE
SyntaxError: Missing initializer in const declaration

### ISSUE THREAD

**Issue by gbourne1** [mjmlio/gulp-mjml#46]
With the new 4.0.0 version get this error when declaring gulp-mjml on Node 12.4.0

const mjml = require('gulp-mjml');

Error:

/node_modules/gulp-mjml/src/index.js:39
      const render;
            ^^^^^^

SyntaxError: Missing initializer in const declaration
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/gulpfile.js:26:9)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)

**Comment by kmcb777** [comment]
Hi @gbourne1 thanks for reporting this, this has been fixed on master

**Comment by kmcb777** [comment]
@gbourne1 it's now released !
