### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jitendravyas** [mjmlio/gulp-mjml#5]
Getting this error

```
18:39:34] Using gulpfile ~/my-projects/mjmlgulp/gulpfile.js
[18:39:34] Starting 'default'...
[18:39:34] Finished 'default' after 8.8 ms
/Users/jitendravyas/my-projects/mjmlgulp/node_modules/gulp-mjml/node_modules/mjml/node_modules/mjml-core/lib/decorators/MJMLElement.js:162
          var childProps = Object.assign({}, child.props);
                                  ^
TypeError: undefined is not a function
    at /Users/jitendravyas/my-projects/mjmlgulp/node_modules/gulp-mjml/node_modules/mjml/node_modules/mjml-core/lib/decorators/MJMLElement.js:162:35
    at Array.forEach (native)
    at MJMLElement._this.renderWrappedOutlookChildren (/Users/jitendravyas/my-projects/mjmlgulp/node_modules/gulp-mjml/node_modules/mjml/node_modules/mjml-core/lib/decorators/MJMLElement.js:161:18)
    at Container.render (/Users/jitendravyas/my-projects/mjmlgulp/node_modules/gulp-mjml/node_modules/mjml/node_modules/mjml-container/lib/index.js:114:9)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/jitendravyas/my-projects/mjmlgulp/node_modules/gulp-mjml/node_modules/mjml/node_modules/mjml-core/node_modules/react/lib/ReactCompositeComponent.js:687:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (/Users/jitendravyas/my-projects/mjmlgulp/node_modules/gulp-mjml/node_modules/mjml/node_modules/mjml-core/node_modules/react/lib/ReactCompositeComponent.js:707:32)
    at wrapper [as _renderValidatedComponent] (/Users/jitendravyas/my-projects/mjmlgulp/node_modules/gulp-mjml/node_modules/mjml/node_modules/mjml-core/node_modules/react/lib/ReactPerf.js:66:21)
    at ReactCompositeComponentMixin.performInitialMount (/Users/jitendravyas/my-projects/mjmlgulp/node_modules/gulp-mjml/node_modules/mjml/node_modules/mjml-core/node_modules/react/lib/ReactCompositeComponent.js:291:30)
    at ReactCompositeComponentMixin.mountComponent (/Users/jitendravyas/my-projects/mjmlgulp/node_modules/gulp-mjml/node_modules/mjml/node_modules/mjml-core/node_modules/react/lib/ReactCompositeComponent.js:222:21)
    at wrapper [as mountComponent] (/Users/jitendravyas/my-projects/mjmlgulp/node_modules/gulp-mjml/node_modules/mjml/node_modules/mjml-core/node_modules/react/lib/ReactPerf.js:66:21)
```

Gulpfile

```
var gulp = require('gulp');
var mjml = require('gulp-mjml')

gulp.task('default', function () {
  gulp.src('./index.mjml')
    .pipe(mjml())
    .pipe(gulp.dest('./html'))
});
```

index.mjml

```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica" align="center">Hello World</mj-text>
          <mj-divider border-color="#F45E43"></mj-divider>
          <mj-text font-size="16px" color="blue" font-family="helvetica">More text</mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by GuillaumeBadi** [comment]
What version of node are you using ?

**Comment by jitendravyas** [comment]
My node version is 5 now. 

I get this error

```
➜  email git:(master) ✗ gulp mjml
[22:46:04] Using gulpfile ~/my-projects/email/gulpfile.js
[22:46:04] Starting 'mjml'...
Warning: Please upgrade your MJML markup to add a <mjml> root tag, <mj-body> as root will no longer be supported soon, see https://github.com/mjmlio/mjml/blob/master/UPGRADE.md
[22:46:04] 'mjml' errored after 126 ms
[22:46:04] Error: no writecb in Transform class
    at afterTransform (/Users/jitendravyas/my-projects/email/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:74:40)
    at TransformState.afterTransform (/Users/jitendravyas/my-projects/email/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at /Users/jitendravyas/my-projects/email/node_modules/gulp-posthtml/index.js:26:17
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
➜  email git:(master) ✗ node -v
v5.11.0
```

**Comment by hadifarnoud** [comment]
same issue here ` v0.12.7 `

**Comment by SilentF** [comment]
I have similar error here 
 var childProps = Object.assign({}, child.props);
                                  ^
TypeError: Object function Object() { [native code] } has no method 'assign'

node version : v4.4.7
npm version : 3.10.5

I installed gulp-mjml via npm and got this error when starting my task

var mjml = require('gulp-mjml')

gulp.task('mjml', function () {
    return gulp.src('./Emails/mjml/welcome2.mjml')
    .pipe(mjml())
    .pipe(gulp.dest('./Emails'))
})

**Comment by fico7489** [comment]
same here

**Comment by meriadec** [comment]
`Object.assign` is part of ES2015 and has been implemented in Node.js since `v4.4.6` (see here: http://node.green/#Object-static-methods).

You can use [babel-polyfill](https://www.npmjs.com/package/babel-polyfill) to use that functionality in older node versions.

```
npm install --save babel-polyfill
```

Then in your source code:

```
require('babel-polyfill')
```
